export const projects = [
  {
    id: 1,
    title: 'Multi-Scale SARS-CoV-2 Transmission Model',
    year: 'July 2025 — Present',
    tags: ['Computational Epidemiology', 'Mathematical Modeling', 'MATLAB', 'Python'],
    description: 'In the fall of 2025 I reached out to Dr. Naveen Vaidya after developing an interest in the mathematics underlying epidemiological modeling. We had a series of conversations about the scope of what I wanted to learn, and together decided to build a modeling framework connecting within-host viral dynamics to between-host transmission risk in SARS-CoV-2, using experimental ferret data.\n\nI developed the model independently under Dr. Vaidya\'s guidance, working across MATLAB and Python. The project is ongoing and details are being withheld ahead of publication.\n\nIn Spring 2026 I gave an oral presentation at the S3 Student Research Symposium, and presented a poster at the San Diego Epidemiology Exchange.',
    collaborators: 'PI: Naveen K. Vaidya · SDSU DiMo Lab',
    link: null,
    linkLabel: null,
    cover: null,
    images: [
      { src: '/projects/s31.jpeg', caption: 'Oral presentation at the S3 Student Research Symposium, Spring 2026' },
      { src: '/projects/s32.jpeg', caption: 'DiMo Lab at S3 Student Research Symposium, 2026' },
      { src: '/projects/epixchange.jpeg', caption: 'San Diego Epidemiology Exchange, 2026' },
    ],
  },
  {
    id: 2,
    title: 'IVPRC Heat Surveillance Dashboard',
    year: '2024',
    tags: ['Public Health', 'Data Engineering', 'Data Visualization'],
    description: 'fill deets',
    collaborators: 'Eyal Oren, Miguel Angel Zavala Perez',
    link: null,
    linkLabel: null,
    cover: null,
    images: [],
  },
  {
    id: 3,
    title: 'Sekeh Lab Deep Learning Bootcamp',
    year: 'July 2025',
    tags: ['Teaching', 'Neural Networks', 'Creative Direction', 'NSF'],
    description: 'In July 2025 I had the chance to be part of the NSF-SDSU-Sekeh Lab Deep Learning Bootcamp brought together students and researchers for a full day of workshops and talks on AI and neural networks! It was organized by my PI, Dr. Salimeh Yasaei Sekeh, with support from the National Science Foundation.\n\nMy research team, Jake Basile and Saad Alrajhi, and I developed and delivered the opening workshop of the day: Introduction to Neural Networks. It was the first time I had taught something I had spent a year learning, which was its own kind of experience. We also had guest speakers from the University of Utah, UT Austin, Voxel51, and SDSU presenting on advanced AI topics throughout the afternoon.\n\nBeyond the research side, I also designed the bootcamp logo, the Sekeh Lab logo, t-shirts, and handouts for the event. Getting to contribute creatively to something academic felt like exactly the kind of work I want to keep doing.',
    collaborators: 'PI: Salimeh Yasaei Sekeh · Jake Basile, Saad Alrajhi, Joshua Andle, Mary Isabelle Wisell, Aditi Naiknaware, Francis Fernandez',
    link: 'https://www.youtube.com/watch?v=uyqLTw3djKk',
    linkLabel: 'Watch the Workshop',
    cover: null,
    images: [],
  },
];
